* Struktura pracy
** Wstęp:
Buddyzm jako filozofia praktyczna, poprzeć cytatem Gotamy o człowieku z zatrutą strzałą w dupsku.
** O buddyzmie w ogóle
** O taoizmie w ogóle
** Specyfika zena soto
** Miejsce jaźni w soto zen
* Cytaty

The Way of Zen (Alan W. Watts)
- Highlight on Page 21 | Loc. 320-24  | Added on Thursday, July 17, 2014, 05:22 PM

The West has no recognized institution corresponding to Taoism because our Hebrew-Christian spiritual tradition identifies the Absolute"God"with the moral and logical order of convention. This might almost be called a major cultural catastrophe, because it weights the social order with excessive authority, inviting just those revolutions against religion and tradition which have been so characteristic of Western history. It is one thing to feel oneself in conflict with socially sanctioned conventions, but quite another to feel at odds with the very root and ground of life, with the Absolute itself.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 22 | Loc. 334-38  | Added on Thursday, July 17, 2014, 05:27 PM

Our very idea of 'spirit' as opposed to 'matter' seems to have more kinship with the abstract than the concrete. But with Taoism, as with other ways of liberation, the Absolute must never be confused with the abstract. On the other hand, if we say that the Tao, as the ultimate Reality is called, is the concrete rather than the abstract, this may lead to still other confusions. For we are accustomed to associate the concrete with the material, the physiological, the biological, and the natural, as distinct from the supernatural. But from the Taoist and Buddhist standpoints these are still terms for conventional and abstract spheres of knowledge.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 27 | Loc. 408-12  | Added on Monday, July 21, 2014, 05:33 PM

Because the natural universe works mainly according to the principles of growth, it would seem quite odd to the Chinese mind to ask how it was made. If the universe were made, there would of course be someone who knows how it is made"who could explain how it was put together bit by bit as a technician can explain in one-at-a-time words how to assemble a machine. But a universe which grows utterly excludes the possibility of knowing how it grows in the clumsy terms of thought and language, so that no Taoist would dream of asking whether the Tao knows how it produces the universe. For it operates according to spontaneity, not according to plan.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 39 | Loc. 584-91  | Added on Tuesday, July 22, 2014, 03:04 PM

Taoism is, then, the original Chinese way of liberation which combined with Indian Mahayana Buddhism to produce Zen. It is a liberation from convention and of the creative power of te. Every attempt to describe and formulate it in words and one-at-a-time thought symbols must, of necessity, distort it. The foregoing chapter has perforce made it seem one of the 'vitalist' or 'naturalistic' philosophical alternatives. For Western philosophers are constantly bedeviled by the discovery that they cannot think outside certain well-worn ruts"that, however hard they may try, their 'new' philosophies turn out to be restatements of ancient positions, monist or pluralist, realist or nominalist, vitalist or mechanist. This is because these are the only alternatives which the conventions of thought can present, and they cannot discuss anything else without presenting it in their own terms. When we try to represent a third dimension upon a two-dimensional surface, it will of necessity seem to belong more or less to the two alternatives of length and breadth. In
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 54 | Loc. 814-16  | Added on Thursday, July 24, 2014, 01:16 AM

The doctrine of maya is therefore a doctrine of relativity. It is saying that things, facts, and events are delineated, not by nature, but by human description, and that the way in which we describe (or divide) them is relative to our varying points of view.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 56 | Loc. 851-53  | Added on Thursday, July 24, 2014, 06:11 PM

Life? s but a walking shadow, a poor player That struts and frets his hour upon the stage And then is heard no more: it is a tale Told by an idiot, full of sound and fury, Signifying nothing.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 61 | Loc. 924-26  | Added on Friday, July 25, 2014, 05:50 PM

It is fundamental to every school of Buddhism that there is no ego, no enduring entity which is the constant subject of our changing experiences. For the ego exists in an abstract sense alone, being an abstraction from memory, somewhat like the illusory circle of fire made by a whirling torch.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 61 | Loc. 929-36  | Added on Friday, July 25, 2014, 06:17 PM

The Second Noble Truth relates to the cause of frustration, which is said to be trishna, clinging or grasping, based on avidya, which is ignorance or unconsciousness. Now avidya is the formal opposite of awakening. It is the state of the mind when hypnotized or spellbound by maya, so that it mistakes the abstract world of things and events for the concrete world of reality. At a still deeper level it is lack of self-knowledge, lack of the realization that all grasping turns out to be the futile effort to grasp oneself, or rather, to make life catch hold of itself. For to one who has self-knowledge, there is no duality between himself and the external world. Avidya is 'ignoring' the fact that subject and object are relational, like the two sides of a coin, so that when one pursues, the other retreats. This is why the egocentric attempt to dominate the world, to bring as much of the world as possible under the control of the ego, has only to proceed for a little while before it raises the difficulty of the ego? s controlling itself.
The Way of Zen (Alan W. Watts)
- Highlight on Page 66 | Loc. 1004-7  | Added on Monday, July 28, 2014, 12:17 AM

samadhi, contemplation, constitute the section dealing with the life of meditation, the inner, mental practice of the Buddha? s way. Complete recollectedness is a constant awareness or watching of one's sensations, feelings, and thoughts"without purpose or comment. It is a total clarity and presence of mind, actively passive, wherein events come and go like reflections in a mirror: nothing is reflected except what is.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 67 | Loc. 1024-30  | Added on Tuesday, July 29, 2014, 12:56 AM

Sitting meditation is not, as is often supposed, a spiritual 'exercise,' a practice followed for some ulterior object. From a Buddhist standpoint, it is simply the proper way to sit, and it seems perfectly natural to remain sitting so long as there is nothing else to be done, and so long as one is not consumed with nervous agitation. To the restless temperament of the West, sitting meditation may seem to be an unpleasant discipline, because we do not seem to be able to sit 'just to sit' without qualms of conscience, without feeling that we ought to be doing something more important to justify our existence. To propitiate this restless conscience, sitting meditation must therefore be regarded as an exercise, a discipline with an ulterior motive. Yet at that: very point it ceases to be meditation (dhyana) in the Buddhist sense, for where there is purpose, where there is seeking and grasping for results, there is no dhyana.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 68 | Loc. 1036-39  | Added on Tuesday, July 29, 2014, 06:44 PM

As used in Buddhism, the term dhyana comprises both recollectedness (smriti) and samadhi, and can best be described as the state of unified or one-pointed awareness. On the one hand, it is one-pointed in the sense of being focused on the present, since to clear awareness there is neither past nor future, but just this one moment (ekaksana) which Western mystics have called the Eternal Now. On the other hand, it is one-pointed in the sense of being a state of consciousness without differentiation of the knower, the knowing, and the known.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 69 | Loc. 1055-56  | Added on Tuesday, July 29, 2014, 06:55 PM

Suffering alone exists, none who suffer; The deed there is, but no doer thereof; Nirvana is, but no one seeking it; The Path there is, but none who travel it. (16)
The Way of Zen (Alan W. Watts)
- Highlight on Page 78 | Loc. 1190-98  | Added on Saturday, August 09, 2014, 06:51 PM

Mahayana philosophy proposes a drastic but effective answer which is the theme of a class of literature called Prajna"paramita, or 'wisdom for crossing to the other shore,' a literature closely associated with the work of Nagarjuna (c. A.D. 200), who ranks with Shankara as one of the greatest minds of India. Stated baldly, the answer is that all grasping, even for nirvana, is futile"for there is nothing to be grasped. This is Nagarjuna? s celebrated Sunyavada, his 'Doctrine of the Void,' otherwise known as the Madhyamika, the 'middle way,' because it refutes all metaphysical propositions by demonstrating their relativity. From the standpoint of academic philosophy, the Prajna-paramita and the doctrine of Nagarjuna are no doubt some form of nihilism or 'absolute relativism.' But this is not Nagarjuna's standpoint. The dialectic with which he demolishes every conception of reality is merely a device for breaking the vicious circle of grasping, and the terminus of his philosophy is not the abject despair of nihilism but the natural and uncontrived bliss (ananda) of liberation.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 79 | Loc. 1208-13  | Added on Saturday, August 09, 2014, 06:52 PM

all things are without 'self-nature' (svabhava) or independent reality since they exist only in relation to other things. Nothing in the universe can stand by itself-no thing, no fact, no being, no event"and for this reason it is absurd to single anything out as the ideal to be grasped. For what is singled out exists only in relation to its own opposite, since what is is defined by what is not, pleasure is defined by pain, life is defined by death, and motion is defined by stillness. Obviously, the mind can form no idea of what 'to be' means without the contrast of 'not to be,' since the ideas of being and non-being are abstractions from such simple experiences as that there is a penny in the right hand and no penny in the left.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 82 | Loc. 1249-52  | Added on Saturday, August 09, 2014, 07:03 PM

when it is clearly understood that all one? s intentional acts-desires, ideals, stratagems-are in vain. In the whole universe, within and without, there is nothing whereon to lay any hold, and no one to lay any hold on anything. This has been discovered through clear awareness of everything that seemed to offer a solution or to constitute a reliable reality, through the intuitive wisdom called prajna, which sees into the relational character of everything. With the 'eye of prajna'
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 84 | Loc. 1275-77  | Added on Sunday, August 10, 2014, 05:16 PM

When we say just 'That' or 'Thus,' we are pointing to the realm of nonverbal experience, to reality as we perceive it directly, for we are trying to indicate what we see or feel rather than what we think or say. Tathata therefore indicates the world just as it is, unscreened and undivided by the symbols and definitions of thought. It points to the concrete and actual as distinct from the abstract and conceptual.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 87 | Loc. 1326-31  | Added on Monday, August 11, 2014, 06:52 PM

each 'thing-event' involves every other, and that the highest insight is simply the perception of them in their natural 'suchness.' At this level every 'thing-event' is seen to be self-determinative, self-generating, or spontaneous, for to be quite naturally what it is, to be tatha"just 'thus'"is to be free and without obstruction. The doctrine of the Dharmadhatu is, approximately, that the proper harmony of the universe is realized when each 'thing-event' is allowed to be freely and spontaneously itself, without interference. Stated more subjectively, it is saying, 'Let everything be free to be just as it is. Do not separate yourself from the world and try to order it around.'
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 89 | Loc. 1364-73  | Added on Tuesday, August 12, 2014, 05:45 PM

The Yogacara does not, therefore, discuss the relation of forms of matter to mind; it discusses the relation of forms to mind, and concludes that they are forms of mind. As a result, the term 'mind' (citta) becomes logically meaningless. But because the main concern of Buddhism is with a realm of experience which is nonlogical and meaningless, in the sense that it does not symbolize or signify anything other than itself, there is no objection to 'meaningless' terms. From the logical standpoint the proposition 'Everything is mind' says no more than that everything is everything. For if there is nothing which is not mind, the word belongs to no class, and has no limits, no definition. One might as well use 'blah'"which is almost exactly what Buddhism does with the nonsense word tathata. For the function of these nonsense terms is to draw our attention to the fact that logic and meaning, with its inherent duality, is a property of thought and language but not of the actual world. The nonverbal, concrete world contains no classes and no symbols which signify or mean anything other than themselves. Consequently it contains no duality. For duality arises only when we classify, when we sort our experiences into mental boxes, since a box is no box without an inside and an outside.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 90 | Loc. 1379-87  | Added on Tuesday, August 12, 2014, 05:50 PM

external and internal, before and after, heavy and light, pleasant and painful, moving and still are all ideas, or mental classifications. Their relation to the concrete world is the same as that of words. Thus the world that we know, when understood as the world as classified, is a product of the mind, and as the sound 'water' is not actually water, the classified world is not the real world. The problem of 'what' the mind is can now be seen to be the same as the problem of 'what' the real world is. It cannot be answered, for every 'what' is a class, and we cannot classify the classifier. Is it not, then, merely absurd to speak of the mind, the citta, at all if there is no way of saying what it is? On the contrary, the mathematician Kurt Gödel has given us a rigorous proof of the fact that every logical system must contain a premise which it cannot define without contradicting itself.11 The Yogacara takes citta as its premise and does not define it, since citta is here the equivalent of sunya and tathata.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 95 | Loc. 1448-52  | Added on Wednesday, August 13, 2014, 06:15 PM

Special flavor of Zen is best described as a certain directness. In other schools of Buddhism, awakening or bodhi seems remote and almost superhuman, something to be reached only after many lives of patient effort. But in Zen there is always the feeling that awakening is something quite natural, something startlingly obvious, which may occur at any moment. If it involves a difficulty, it is just that it is much too simple. Zen is also direct in its way of teaching, for it points directly and openly to the truth, and does not trifle with symbolism.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 123 | Loc. 1872-81  | Added on Monday, August 18, 2014, 06:50 PM

Nothing, however, is more difficult than establishing proper qualifications in the imponderable realm of spiritual insight. Where the candidates are few the problem is not so grave, but where one master is responsible for some hundreds of students the process of teaching and testing requires standardization. Zen solved this problem with remarkable ingenuity, employing a means which not only provided a test of competence but"what was much more"a means of transmitting the Zen experience itself with a minimum of falsification. This extraordinary invention was the system of the kung-an ee (Japanese, koan) or 'Zen problem.' Literally, this term means a 'public document' or 'case' in the sense of a decision creating a legal precedent. Thus the koan system involves 'passing' a series of tests based on the mondo or anecdotes of the old masters. One of the beginning koans is Chao-chou? s answer 'Wu' or 'No' to the question as to whether a dog has Buddha nature. The student is expected to show that he has experienced the meaning of the koan by a specific and usually nonverbal demonstration which he has to discover intuitively.42
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 124 | Loc. 1'-96  | Added on Monday, August 18, 2014, 07:04 PM

both the question and its answer, for the student is expected to see into the relationship between the two, which, to say the least, is none too obvious. For the moment, it is enough to say that every koan has a 'point' which is some aspect of Zen experience, that its point is often concealed by being made very much more apparent than one would expect, and that koans are concerned not only with the primary awakening to the Void but also with its subsequent expression in life and thought.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 125 | Loc. 1908-17  | Added on Monday, August 18, 2014, 07:06 PM

It should be noted that Zen arrived in Japan shortly after the beginning of the Kamakura Era, when the military dictator Yoritomo and his samurai followers had seized power from the hands of the then somewhat decadent nobility. This historical coincidence provided the military class, the samurai, with a type of Buddhism which appealed to them strongly because of its practical and earthy qualities and because of the directness and simplicity of its approach. Thus there arose that peculiar way of life called bushido, the Tao of the warrior, which is essentially the application of Zen to the arts of war. The association of the peace-loving doctrine of the Buddha with the military arts has always been a puzzle to Buddhists of other schools. It seems to involve the complete divorce of awakening from morality. But one must face the fact that, in its essence, the Buddhist experience is a liberation from conventions of every kind, including the moral conventions. On the other hand, Buddhism is not a revolt against convention, and in societies where the military caste is an integral part of the conventional structure and the warrior? s role an accepted necessity Buddhism will make it possible for him to fulfill that role as a Buddhist. The medieval cult of chivalry should be no less of a puzzle to the peace-loving Christian.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 126 | Loc. 1919-21  | Added on Monday, August 18, 2014, 07:07 PM

For by the genius of such Zen monks as Dogen, Hakuin, and Bankei, by such poets as Ryokan and Basho, and by such a painter as Sesshu, Zen has been made extraordinarily accessible to the common mind.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 127 | Loc. '3-54  | Added on Monday, August 18, 2014, 07:10 PM

The history of Chinese Zen raises one problem of great fascination. Both Rinzai and Soto Zen as we find them in Japanese monasteries today put enormous emphasis on za-zen or sitting meditation, a practice which they follow for many hours of the day"attaching great importance to the correctness of posture and the way of breathing which it involves. To practice Zen is, to all intents and purposes, to practice za-zen, to which the Rinzai School adds sanzen, the periodic visits to the master (roshi) for presenting one? s view of the koan. However, the Shen-hui Ho-chang I-chi records the following conversation between Shen-hui and a certain Ch'eng: The Master asked Dhyana Master Ch'eng: 'What method must be practiced to see into one's own nature' 'It is first of all necessary to apply oneself to the practice of sitting cross-legged in samadhi. Once samadhi is obtained, one must, by means of samadhi, awaken prajna in oneself. By prajna one is able to see into one's own nature.' (Shen-hui:) 'When one practices samadhi, isn't this a deliberate activity of the mind' (Ch'eng:) 'Yes.' (Shen-hui:) 'Then this deliberate activity of the mind is an activity of restricted consciousness, and how can it bring seeing into one's own nature' (Ch'eng:) 'To see into one's own nature, it is necessary to practice samadhi. How could one see it otherwise' (Shen-hui:) 'All practice of samadhi is fundamentally a wrong view. How, by practicing samadhi, could one attain samadhi' (1.111) We have already mentioned the incident between Ma-tsu and Huai-jang, in which the latter compared sitting in meditation to polishing a tile for a mirror. On another occasion Huai-jang said: To train yourself in sitting meditation [za-zen] is to train yourself to be a sitting Buddha. If you train yourself in za-zen, (you should know that) Zen is neither sitting nor lying. If you train yourself to be a sitting Buddha, (you should know that) the Buddha is not a fixed form. Since the Dharma has no (fixed) abode, it is not a matter of making choices. If you (make yourself) a sitting Buddha this is precisely killing the Buddha. If you adhere to the sitting position, you will not attain the principle (of Zen).46 gg
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 141 | Loc. 2158-65  | Added on Tuesday, August 19, 2014, 11:50 PM

the viewpoint is not fatalistic. It is not simply submission to the inevitability of sweating when it is hot, shivering when it is cold, eating when hungry, and sleeping when tired. Submission to fate implies someone who submits, someone who is the helpless puppet of circumstances, and for Zen there is no such person. The duality of subject and object, of the knower and the known, is seen to be just as relative, as mutual, as inseparable as every other. We do not sweat because it is hot; the sweating is the heat. It is just as true to say that the sun is light because of the eyes as to say that the eyes see light because of the sun. The viewpoint is unfamiliar because it is our settled convention to think that heat comes first and then, by causality, the body sweats. To put it the other way round is startling, like saying 'cheese and bread' instead of 'bread and cheese.' Thus the Zenrin Kushu says: Fire does not wait for the sun to be hot Nor the wind for the moon, to be cool.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 142 | Loc. 2172-81  | Added on Tuesday, August 19, 2014, 11:52 PM

To put it less poetically"human experience is determined as much by the nature of the mind and the structure of its senses as by the external objects whose presence the mind reveals. Men feel themselves to be victims or puppets of their experience because they separate 'themselves' from their minds, thinking that the nature of the mind-body is something involuntarily thrust upon 'them.' They think that they did not ask to be born, did not ask to be 'given' a sensitive organism to be frustrated by alternating pleasure and pain. But Zen asks us to find out 'who' it is that 'has' this mind, and 'who' it was that did not ask to be born before father and mother conceived us. Thence it appears that the entire sense of subjective isolation, of being the one who was 'given' a mind and to whom experience happens, is an illusion of bad semantics"the hypnotic suggestion of repeated wrong thinking. For there is no 'myself' apart from the mind-body which gives structure to my experience. It is likewise ridiculous to talk of this mind-body as something which was passively and involuntarily 'given' a certain structure. It is that structure, and before the structure arose there was no mind-body.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 143 | Loc. 2182-88  | Added on Wednesday, August 20, 2014, 05:15 PM

Because the idea is so much more comprehensible than the reality, the symbol so much more stable than the fact, we learn to identify ourselves with our idea of ourselves. Hence the subjective feeling of a 'self' which 'has' a mind, of an inwardly isolated subject to whom experiences involuntarily happen. With its characteristic emphasis on the concrete, Zen points out that our precious 'self' is just an idea, useful and legitimate enough if seen for what it is, but disastrous if identified with our real nature. The unnatural awkwardness of a certain type of self-consciousness comes into being when we are aware of conflict or contrast between the idea of ourselves, on the one hand, and the immediate, concrete feeling of ourselves, on the other.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 143 | Loc. 2'-94  | Added on Wednesday, August 20, 2014, 05:36 PM

in concrete fact I have no other self than the totality of things of which I am aware. This is the Hua-yen (Kegon) doctrine of the net of jewels, of shih shih wu ai (Japanese, ji ji mu ge), in which every jewel contains the reflection of all the others.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 146 | Loc. 2234-38  | Added on Wednesday, August 20, 2014, 05:42 PM

Life is a position of time. Death is a position of time. They are like winter and spring, and in Buddhism we do not consider that winter becomes spring, or that spring becomes summer.9 Dogen is here trying to express the strange sense of timeless moments which arises when one is no longer trying to resist the flow of events, the peculiar stillness and self-sufficiency of the succeeding instants when the mind is, as it were, going along with them and not trying to arrest them.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 147 | Loc. 2247-51  | Added on Wednesday, August 20, 2014, 05:47 PM

Connected, then, with the pursuit of the good is the pursuit of the future, the illusion whereby we are unable to be happy without a 'promising future' for the symbolic self. Progress towards the good is therefore measured in terms of the prolongation of human life, forgetting that nothing is more relative than our sense of the length of time. A Zen poem says: The morning glory which blooms for an hour Differs not at heart from the giant pine, Which lives for a thousand years.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 148 | Loc. 2268-78  | Added on Wednesday, August 20, 2014, 05:51 PM

This is not a philosophy of not looking where one is going; it is a philosophy of not making where one is going so much more important than where one is that there will be no point in going. The life of Zen begins, therefore, in a disillusion with the pursuit of goals which do not really exist"the good without the bad, the gratification of a self which is no more than an idea, and the morrow which never comes. For all these things are a deception of symbols pretending to be realities, and to seek after them is like walking straight into a wall upon which some painter has, by the convention of perspective, suggested an open passage. In short, Zen begins at the point where there is nothing further to seek, nothing to be gained. Zen is most emphatically not to be regarded as a system of self-improvement, or a way of becoming a Buddha. In the words of Lin-chi, 'If a man seeks the Buddha, that man loses the Buddha.' For all ideas of self-improvement and of becoming or getting something in the future relate solely to our abstract image of ourselves. To follow them is to give ever more reality to that image. On the other hand, our true, nonconceptual self is already the Buddha, and needs no improvement. In the course of time it may grow, but one does not blame an egg for not being a chicken; still less does one criticize a pig for having a shorter neck than a giraffe.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 150 | Loc. 2297-2306  | Added on Wednesday, August 20, 2014, 06:09 PM

The difficulty of Zen is, of course, to shift one? s attention from the abstract to the concrete, from the symbolic self to one's true nature. So long as we merely talk about it, so long as we turn over ideas in our minds about 'symbol' and 'reality,' or keep repeating, 'I am not my idea of myself,' this is still mere abstractíon. Zen created the method (upaya) of 'direct pointing' in order to escape from this vicious circle, in order to thrust the real immediately to our notice. When reading a difficult book it is of no help to think, 'I should concentrate,' for one thinks about concentration instead of what the book has to say. Likewise, in studying or practicing Zen it is of no help to think about Zen. To remain caught up in ideas and words about Zen is, as the old masters say, to 'stink of Zen.' For this reason the masters talk about Zen as little as possible, and throw its concrete reality straight at us. This reality is the 'suchness' (tathata) of our natural, nonverbal world. If we see this just as it is, there is nothing good, nothing bad, nothing inherently long or short, nothing subjective and nothing objective. There is no symbolic self to be forgotten, and no need for any idea of a concrete reality to be remembered.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 155 | Loc. 2368-79  | Added on Saturday, August 23, 2014, 05:40 PM

At once it is clear that 'sameness' and 'difference' are abstractions. The same would have to be said of all categorizations of the concrete world"even 'concrete' itself"for such terms as 'physical,' 'material,' 'objective,' 'real,' and 'existential' are extremely abstract symbols. Indeed, the more one tries to define them, the more meaningless they turn out to be. The world of 'suchness' is void and empty because it teases the mind out of thought, dumfounding the chatter of definition so that there is nothing left to be said. Yet it is obvious that we are not confronted with literal nothingness. It is true that, when pressed, every attempt to catch hold of our world leaves us empty-handed. Furthermore, when we try to be sure at least of ourselves, the knowing, catching subjects, we disappear. We cannot find any self apart from the mind, and we cannot find any mind apart from those very experiences which the mind"now vanished"was trying to grasp. In R. H. Blyth? s arresting metaphor, when we were just about to swat the fly, the fly flew up and sat on the swatter. In terms of immediate perception, when we look for things there is nothing but mind, and when we look for mind there is nothing but things. For a moment we are paralyzed, because it seems that we have no basis for action, no ground under foot from which to take a jump. But this is the way it always was, and in the next moment we find ourselves as free to act, speak, and think as ever, yet in a strange and miraculous new world from which 'self' and 'other,' 'mind' and 'things' have vanished.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 161 | Loc. 2460-64  | Added on Wednesday, August 27, 2014, 05:33 PM

In its stress upon naturalness, Zen is obviously the inheritor of Taoism, and its view of spontaneous action as 'marvelous activity' (miao-yung d) is precisely what the Taoists meant by the word te or 'virtue' with an overtone of magical power. But neither in Taoism nor in Zen does it have anything to do with magic in the merely sensational sense of performing superhuman 'miracles.' The 'magical' or 'marvelous' quality of spontaneous action is, on the contrary, that it is perfectly human, and yet shows no sign of being contrived.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 162 | Loc. 2477-87  | Added on Thursday, August 28, 2014, 02:30 PM

Thus to try to be natural is an affectation. To try not to try to be natural is also an affectation. As a Zenrin poem says: You cannot get it by taking thought; You cannot seek it by not taking thought.e But this absurdly complex and frustrating predicament arises from a simple and elementary mistake in the use of the mind. When this is understood, there is no paradox and no difficulty. Obviously, the mistake arises in the attempt to split the mind against itself, but to understand this clearly we have to enter more deeply into the 'cybernetics' of the mind, the basic pattern of its self-correcting action. It is, of course, part of the very genius of the human mind that it can, as it were, stand aside from life and reflect upon it, that it can be aware of its own existence, and that it can criticize its own processes. For the mind has something resembling a 'feed-back' system. This is a term used in communications engineering for one of the basic principles of 'automation,' of enabling machines to control themselves. Feed-back enables a machine to be informed of the effects of its own action in such a way as to be able to correct its action. Perhaps the most familiar example is the electrical thermostat which regulates the heating of a house. By setting an upper and a lower limit of desired temperature, a thermometer is so connected that it will switch the furnace on when the lower limit is reached, and off when the upper limit is reached. The temperature of the house is thus kept within the desired limits. The thermostat provides the furnace with a kind of sensitive organ"an extremely rudimentary analogy of hurnan self-consciousness.2 The proper adjustment of a feed-back system is always a complex mechanical problem. For the original machine, say, the furnace, is adjusted by the feed-back system, but this system in turn needs adjustment. Therefore to make a mechanical system more and more automatic will require the use of a series of feed-back systems"a second to correct the first, a third to correct the second, and so on. But there are obvious limits to such a series, for beyond a certain point the mechanism will be 'frustrated' by its own complexity. For example, it might take so long for the information to pass through the series of control systems that it would arrive at the original machine too late to be useful. Similarly, when human beings think too carefully and minutely about an action to be taken, they cannot make up their minds in time to act. In other words, one cannot correct one? s means of self-correction indefinitely. There must soon be a source of information at the end of the line which is the final authority. Failure to trust its authority will make it impossible to act, and the system will be paralyzed. The system can be paralyzed in yet another way. Every feedback system needs a margin of 'lag' or error. If we try to make a thermostat absolutely accurate"that is, if we bring the upper and lower limits of temperature very close together in an attempt to hold the temperature at a constant 70 degrees"the whole system will break down. For to the extent that the upper and lower limits coincide, the signals for switching off and switching on will coincide! If 70 degrees is both the lower and upper limit the 'go' sign will also be the 'stop' sign; 'yes' will imply 'no' and 'no' will imply 'yes.' Whereupon the mechanism will start 'trembling,' going on and off, on and off, until it shakes itself to pieces. The system is too sensitive and shows symptoms which are startlingly like human anxiety. For when a human being is so self-conscious, so self-controlled that he cannot let go of himself, he dithers or wobbles between opposites. This is precisely what is meant in Zen by going round and round on 'the wheel of birth-and-death,' for the Buddhist samsara is the prototype of all vicious circles.3
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 164 | Loc. 2513-20  | Added on Thursday, August 28, 2014, 06:52 PM

But to keep up the supply of information in the memory, the mind-body must continue to act 'on its own.' It must not cling too closely to its own record. There must be a 'lag' or distance between the source of information and the source of action. This does not mean that the source of action must hesitate before it accepts the information. It means that it must not identify itself with the source of information. We saw that when the furnace responds too closely to the thermostat, it cannot go ahead without also trying to stop, or stop without also trying to go ahead. This is just what happens to the human being, to the mind, when the desire for certainty and security prompts identification between the mind and its own image of itself. It cannot let go of itself. It feels that it should not do what it is doing, and that it should do what it is not doing. It feels that it should not be what it is, and be what it isn? t. Furthermore, the effort to remain always 'good' or 'happy' is like trying to hold the thermostat to a constant 70 degrees by making the lower limit the same as the upper.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 166 | Loc. 2535-40  | Added on Monday, September 01, 2014, 04:59 PM

reflection about reflection is also action"provided that in doing it we do just that, and do not tend to drift off into the infinite regression of trying always to stand above or outside the level upon which we are acting. Thus Zen is also a liberation from the dualism of thought and action, for it thinks as it acts"with the same quality of abandon, commitment, or faith. The attitude of wu-hsin is by no means an anti-intellectualist exclusion of thinking. Wu-hsin is action on any level whatsoever, physical or psychic, without trying at the same moment to observe and check the action from outside. This attempt to act and think about the action simultaneously is precisely the identification of the mind with its idea of itself. It involves the same contradiction as the statement which states something about itself"'This statement is false.'
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 167 | Loc. 2549-53  | Added on Monday, September 01, 2014, 05:03 PM

In the end, the only alternative to a shuddering paralysis is to leap into action regardless of the consequences. Action in this spirit may be right or wrong with respect to conventional standards. But our decisions upon the conventional level must be supported by the conviction that whatever we do, and whatever 'happens' to us, is ultimately 'right.' In other words, we must enter into it without 'second thought,' without the arriere-pensée of regret, hesitancy, doubt, or self-recrimination. Thus when Yün-men was asked, 'What is the Tao' he answered simply, 'Walk on! (ch? ü f).'
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 167 | Loc. 2549-55  | Added on Monday, September 01, 2014, 05:08 PM

In the end, the only alternative to a shuddering paralysis is to leap into action regardless of the consequences. Action in this spirit may be right or wrong with respect to conventional standards. But our decisions upon the conventional level must be supported by the conviction that whatever we do, and whatever 'happens' to us, is ultimately 'right.' In other words, we must enter into it without 'second thought,' without the arriere-pensée of regret, hesitancy, doubt, or self-recrimination. Thus when Yün-men was asked, 'What is the Tao' he answered simply, 'Walk on! (ch? ü f).' But to act 'without second thought,' without double-mindedness, is by no means a mere precept for our imitation. For we cannot realize this kind of action until it is clear beyond any shadow of doubt that it is actually impossible to do anything else.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 169 | Loc. 2591-99  | Added on Monday, September 01, 2014, 05:20 PM

Social conditioning fosters the identification of the mind with a fixed idea of itself as the means of self-control, and as a result man thinks of himself as 'I'"the ego. Thereupon the mental center of gravity shifts from the spontaneous or original mind to the ego image. Once this has happened, the very center of our psychic life is identified with the self-controlling mechanism. It then becomes almost impossible to see how 'I' can let go of 'myself,' for I am precisely my habitual effort to hold on to myself. I find myself totally incapable of any mental action which is not intentional, affected, and insincere. Therefore anything I do to give myself up, to let go, will be a disguised form of the habitual effort to hold on. I cannot be intentionally unintentional or purposely spontaneous. As soon as it becomes important for me to be spontaneous, the intention to be so is strengthened; I cannot get rid of it, and yet it is the one thing that stands in the way of its own fulfillment. It is as if someone had given me some medicine with the warning that it will not work if I think of a monkey while taking it.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 173 | Loc. 2640-44  | Added on Monday, September 01, 2014, 05:26 PM

To the logician it will of course seem that the point at which we have arrived is pure nonsense"as, in a way, it is. From the Buddhist point of view, reality itself has no meaning since it is not a sign, pointing to something beyond itself. To arrive at reality"at 'suchness'"is to go beyond karma, beyond consequential action, and to enter a life which is completely aimless. Yet to Zen and Taoism alike this is the very life of the universe, which is complete at every moment and does not need to justify itself by aiming at something beyond.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 173 | Loc. 2651-58  | Added on Monday, September 01, 2014, 05:28 PM

Furthermore, the Zen experience is more of a conclusion than a premise. It is never to be used as the first step in a line of ethical or metaphysical reasoning, since conclusions draw to it rather than from it. Like the Beatific Vision of Christianity, it is a 'which than which there is no whicher'"the true end of man"not a thing to be used for some other end. Philosophers do not easily recognize that there is a point where thinking-like boiling an egg-must come to a stop. To try to formulate the Zen experience as a proposition"'everything is the Tao'"and then to analyze it and draw conclusions from it is to miss it completely. Like the Crucifixion, it is 'to the Jews [the moralists] a stum-blingblock and to the Greeks [the logicians] foolishness.' To say that 'everything is the Tao' almost gets the point, but just at the moment of getting it, the words crumble into nonsense. For we are here at a limit at which words break down because they always imply a meaning beyond themselves"and here there is no meaning beyond.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 174 | Loc. 2662-65  | Added on Monday, September 01, 2014, 05:29 PM

Zen lies beyond the ethical standpoint, whose sanctions must be found, not in reality itself, but in the mutual agreement of human beings. When we attempt to universalize or absolutize it, the ethical standpoint makes it impossible to exist, for we cannot live for a day without destroying the life of some other creature.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 174 | Loc. 2668-71  | Added on Monday, September 01, 2014, 05:31 PM

human relations are the sphere of Confucianism rather than Zen, but since the Sung dynasty (959"1278) Zen has consistently fostered Confucianism and was the main source of the introduction of its principles into Japan. It saw their importance for creating the type of cultural matrix in which Zen could flourish without coming into conflict with social order, because the Confucian ethic is admittedly human and relative, not divine and absolute.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 176 | Loc. 2'-2702  | Added on Monday, September 01, 2014, 05:42 PM

Suzuki has translated a long letter from the Zen master Takuan on the relationship of Zen to the art of fencing, and this is certainly the best literary source of what Zen means by mo chih ch? u, by 'going straight ahead without stopping.'13 Both Takuan and Bankei stressed the fact that the 'original' or 'unborn' mind is constantly working miracles even in the most ordinary person. Even though a tree has innumerable leaves, the mind takes them in all at once without being 'stopped' by any one of them. Explaining this to a visiting monk, Bankei said, 'To prove that your mind is the Buddha mind, notice how all that I say here goes into you without missing a single thing, even though I don't try to push it into you.'14 When heckled by an aggressive Nichiren monk who kept insisting that he couldn't understand a word, Bankei asked him to come closer. The monk stepped forward, 'Closer still,' said Bankei. The monk came forward again. 'How well,' said Bankei, 'you understand me!'15 In other words, our natural organism performs the most marvelously complex activities without the least hesitation or deliberation. Conscious thought is itself founded upon its whole system of spontaneous functioning, for which reason there is really no alternative to trusting oneself completely to its working. Oneself is its working.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 183 | Loc. 2797-2801  | Added on Tuesday, September 02, 2014, 12:55 AM

To put it in another way: one does not practice Zen to become a Buddha; one practices it because one is a Buddha from the beginning"and this 'original realization' is the starting point of the Zen life. Original realization is the 'body' (t? i b) and the marvelous practice the 'use' (yung c), and the two correspond respectively to prajna, wisdom, and karuna, the compassionate activity of the awakened Bodhisattva in the world of birth-and-death.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 183 | Loc. 2803-11  | Added on Tuesday, September 02, 2014, 12:56 AM

We have seen that"whatever may have been the practice of the Tang masters"the modern Zen communities, both Soto and Rinzai, attach the highest importance to meditation or 'sitting Zen' (za-zen). It may seem both strange and unreasonable that strong and intelligent men should simply sit still for hours on end. The Western mentality feels that such things are not only unnatural but a great waste of valuable time, however useful as a discipline for inculcating patience and fortitude. Although the West has its own contemplative tradition in the Catholic Church, the life of 'sitting and looking' has lost its appeal, for no religion is valued which does not 'improve the world,' and it is hard to see how the world can be improved by keeping still. Yet it should be obvious that action without wisdom, without clear awareness of the world as it really is, can never improve anything. Furthermore, as muddy water is best cleared by leaving it alone, it could be argued that those who sit quietly and do nothing are making one of the best possible contributions to a world in turmoil.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 184 | Loc. 2821-24  | Added on Tuesday, September 02, 2014, 12:57 AM

It is simply a quiet awareness, without comment, of whatever happens to be here and now. This awareness is attended by the most vivid sensation of 'nondifference' between oneself and the external world, between the mind and its contents"the various sounds, sights, and other impressions of the surrounding environment. Naturally, this sensation does not arise by trying to acquire it; it just comes by itself when one is sitting and watching without any purpose in mind"even the purpose of getting rid of purpose.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page ' | Loc. '9-41  | Added on Tuesday, September 02, 2014, 05:59 PM

The basic position of Zen is that it has nothing to say, nothing to teach. The truth of Buddhism is so self-evident, so obvious that it is, if anything, concealed by explaining it. Therefore the master does not 'help' the student in any way, since helping would actually be hindering. On the contrary, he goes out of his way to put obstacles and barriers in the student? s path.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 205 | Loc. 3139-46  | Added on Sunday, September 07, 2014, 12:17 PM

Taoism, Confucianism, and Zen are expressions of a mentality which feels completely at home in this universe, and which sees man as an integral part of his environment. Human intelligence is not an imprisoned spirit from afar but an aspect of the whole intricately balanced organism of the natural world, whose principles were first explored in the Book of Changes. Heaven and earth are alike members of this organism, and nature is as much our father as our mother, since the Tao by which it works is originally manifested in the yang and the yin"the male and female, positive and negative principles which, in dynamic balance, maintain the order of the world. The insight which lies at the root of Far Eastern culture is that opposites are relational and so fundamentally harmonious. Conflict is always comparatively superficial, for there can be no ultimate conflict when the pairs of opposites are mutually interdependent. Thus our stark divisions of spirit and nature, subject and object, good and evil, artist and medium are quite foreign to this culture.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 207 | Loc. 3171-81  | Added on Sunday, September 07, 2014, 12:23 PM

the Zen monasteries became leading centers of Chinese scholarship. Lay scholars, Confucian and Taoist alike, visited them for periods of study, and Zen monks in turn familiarized themselves with Chinese classical studies. Since writing and poetry were among the chief preoccupations of Chinese scholars, and since the Chinese way of painting is closely akin to writing, the roles of scholar, artist, and poet were not widely separated. The Chinese gentleman-scholar was not a specialist, and it was quite against the nature of the Zen monk to confine his interests and activities to purely 'religious' affairs. The result was a tremendous cross-fertilization of philosophical, scholarly, poetic, and artistic pursuits in which the Zen and Taoist feeling for 'naturalness' became the dominant note. It was during this same period that Eisai and Dogen came from Japan to return with Zen to their own country, to be followed by an incessant stream of Japanese scholar-monks eager to take home not only Zen but every other aspect of Chinese culture. Shiploads of monks, amounting almost to floating monasteries, plied between China and Japan, carrying not only sutras and Chinese classical books, but also tea, silk, pottery, incense, paintings, drugs, musical instruments, and every refinement of Chinese culture"not to mention Chinese artists and craftsmen.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 215 | Loc. 3291-94  | Added on Sunday, September 07, 2014, 05:35 PM

This is in the spirit of Nan-ch? üan's saying, 'The ordinary mind is the Tao'"where 'ordinary' means 'simply human' rather than 'merely vulgar.' It was thus that the seventeenth century saw an extraordinary popularization of the Zen atmosphere in Japan, reaching down from the monks and samurai to farmers and artisans.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 216 | Loc. 3298-99  | Added on Sunday, September 07, 2014, 05:36 PM

haiku sees things in their 'suchness,' without comment"a view of the world which the Japanese call sono-mama, 'Just as it is,' or 'Just so.'
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 231 | Loc. 3534-39  | Added on Sunday, September 07, 2014, 06:38 PM

In its own way, each one of the arts which Zen has inspired gives vivid expression to the sudden or instantaneous quality of its view of the world. The momentariness of sumi paintings and haiku, and the total presence of mind required in cha-no-yu and kendo, bring out the real reason why Zen has always called itself the way of instantaneous awakening. It is not just that satori comes quickly and unexpectedly, all of a sudden, for mere speed has nothing to do with it. The reason is that Zen is a liberation from time. For if we open our eyes and see clearly, it becomes obvious that there is no other time than this instant, and that the past and the future are abstractions without any concrete reality.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 232 | Loc. 3549-57  | Added on Monday, September 08, 2014, 08:42 AM

However, it is not as if the superficial consciousness were one thing, and the 'original mind' another, for the former is a specialized activity of the latter. Thus the superficial consciousness can awaken to the eternal present if it stops grasping. But this does not come to pass by trying to concentrate on the present"an effort which succeeds only in making the moment seem ever more elusive and fleeting, ever more impossible to bring into focus. Awareness of the 'eternal now' comes about by the same principle as the clarity of hearing and seeing and the proper freedom of the breath. Clear sight has nothing to do with trying to see; it is just the realization that the eyes will take in every detail all by themselves, for so long as they are open one can hardly prevent the light from reaching them. In the same way, there is no difficulty in being fully aware of the eternal present as soon as it is seen that one cannot possibly be aware of anything else"that in concrete fact there is no past or future. Making an effort to concentrate on the instantaneous moment implies at once that there are other moments. But they are nowhere to be found, and in truth one rests as easily in the eternal present as the eyes and ears respond to light and sound.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 233 | Loc. 3564-66  | Added on Monday, September 08, 2014, 08:44 AM

There is only this now. It does not come from anywhere; it is not going anywhere. It is not permanent, but it is not impermanent. Though moving, it is always still. When we try to catch it, it seems to run away, and yet it is always here and there is no escape from it. And when we turn round to find the self which knows this moment, we find that it has vanished like the past.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 233 | Loc. 3567-72  | Added on Monday, September 08, 2014, 08:45 AM

In this moment there is nothing which comes to be. In this moment there is nothing which ceases to be. Thus there is no birth-and-death to be brought to an end. Wherefore the absolute tranquillity (of nirvana) is this present moment. Though it is at this moment, there is no limit to this moment, and herein is eternal delight. (7) k Yet, when it comes to it, this moment can be called 'present' only in relation to past and future, or to someone to whom it is present. But when there is neither past nor future, and no one to whom this moment is present, what is it? When Fa-ch? ang was dying, a squirrel screeched on the roof. 'It's just this,' he said, 'and nothing else.'
==========
The Joyous Cosmology (Alan Watts)
- Highlight on Page 13 | Loc. 186-89  | Added on Friday, September 26, 2014, 06:55 AM

Taoism and Zen Buddhism,do not presuppose a universe divided into the spiritual and the material, and do not culminate in a state of consciousness where the physical world vanishes into some undifferentiated and bodiless luminescence. Taoism and Zen are alike founded upon a philosophy of relativity, but this philosophy is not merely speculative. It is a discipline in awareness as a result of which the mutual interrelation of all things and all events becomes a constant sensation.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 15 | Loc. 219-32  | Added on Wednesday, January 14, 2015, 04:07 PM

Zen teaches that we are living in paradise right now, even amid all the shit that? s going down. This world is the Pure Land. This world is paradise. In fact, this world is better than paradise,but all we can do is piss and moan, and look around for something better. But it's not just 'Buddhism' or 'Zen' that says that. It's me, right now to you. And I'll say it again: This world is better than paradise, better than any Utopia you can imagine. I say that in the face of war and starvation and suicide bombings and Orange Terror Alerts. This world is better than Utopia because,and follow this point carefully,you can never live in Utopia. Utopia is always somewhere else. That's the very definition of Utopia. Maybe you can go to a paradisiacal island, far away from your boss and your bills and anything else you want, but pretty soon you'll be complaining that you've got sand up your ass, or the snack machine ate your dollar, or hermit crabs stole your thongs. You'll always find something wrong with wherever you are because it will never quite match your idea of what it 'should' be. You can't go to paradise. Not now and not after you make your first million. Not after you die. And not if you eat all your peas and are really, really good. Not ever. What you call 'you' can never enter the gates of heaven, no matter how convictedly you believe. Heaven and paradise aren't in your future because you have no future. There is no future for you. There is no future for anyone. There is no future at all. Future is an idea. You can't live in paradise,but you are living right here. Make this your paradise or make this your hell. The choice is entirely yours. Really.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 65 | Loc. 982-93  | Added on Monday, January 19, 2015, 09:43 PM

Prajna is intuitive wisdom, and it has nothing at all to do with knowledge. Prajna ain? t book learnin'. The word intuition is used a lot these days to refer to a kind of gut feeling, and that's something like what prajna is,but it's more than that: it's a direct knowing. You're thinking with body and mind together. Regular thinking is only mental action, but prajna includes the physical as well. It's also a mistake to regard prajna as emotional. Emotion itself can often be a kind of confusion. Once a feeling becomes so strong we start calling it an emotion, it's already become too powerful to deal with in any clear-eyed manner. Prajna includes feeling, but it's feeling on a more subtle level. Think about anger. Everyone experiences a flash of anger welling up in some circumstance or other. But anger can only continue to grow when it's fed by thought. Prajna is the wisdom to notice anger before it becomes a problem, to see clearly why you feel angry and what that feeling of anger really is (and is not). This goes much deeper than just saying, 'I'm angry because he called me a panty-waist with carburetor breath.' Why does an insult make you angry? Who is the 'you' that has been insulted? What is the 'you' that can get angry? Prajna is the wisdom to get at the very root of any emotional response. Prajna is developed through the practice of zazen.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 67 | Loc. 1013-23  | Added on Monday, January 19, 2015, 09:48 PM

Emptiness is the single most misunderstood word in all of Buddhism. The original Sanskrit word for this is shunyata, which ultimately points to the as-it-is-ness of things, the state of things being as they are without being colored by our views and ideas. But really, no matter how you define this word, it is still used to express something for which there simply were and are no adequate words, definitions, or concepts. The set of tools we? re given to write about Buddhism are simply not up to the task. Nor were they up to the task 2,500 years ago. Emptiness is not a nihilistic concept of voidness. Emptiness is not meaninglessness. Emptiness is that condition which is free from our conceptions and our perceptions. It's the world as it is before we come along and start complaining about the stuff we don't like. Nishijima translates the famous line 'Form is emptiness, emptiness is form,' as, 'Matter is the immaterial, the immaterial is matter.' John Lennon expressed the same idea in Everybody's Got Something to Hide Except for Me and My Monkey: 'Your inside is out and your outside is in.' The world we perceive and the thing that perceives the world are one and the same. Another modern Indian teacher, a guy named Krishnamurti, was fond of saying, 'The observer is the observed.'
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 70 | Loc. 1065-70  | Added on Monday, January 19, 2015, 09:54 PM

The usual understanding is that the first truth is that all life suffers. Gautama Buddha actually used the word dukkha, a word in the Pali language meaning something more like 'unsatisfactory experience.' The second noble truth is traditionally interpreted as saying that the origination of suffering is desire. The third truth is usually understood to say that stopping desire leads to the stopping of suffering. The fourth is the truth of the Right Way, usually given in the form of the noble eightfold path, which leads to the stopping of desire. The eight 'folds' are these: right understanding, right thought, right speech, right action, right livelihood, right effort, right mindfulness, and right concentration.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 73 | Loc. 1108-10  | Added on Tuesday, January 20, 2015, 11:43 PM

The past and the future,even the present,are just inventions by the conscious mind for dealing with reality in an organized way. They're symbolic representations. And representations aren't reality.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 76 | Loc. 1152-55  | Added on Tuesday, January 20, 2015, 11:49 PM

Everything exists in this moment. This moment is the basis of all creation. The universe wasn't created the Biblical six thousand years ago or even the scientific fifteen billion. The universe is created right now and right now it disappears. Before you even have time to recognize its existence, it's gone forever. Yet the present moment penetrates all of time and space. In Dogen's words, 'What is happening here and now is obstructed by happening itself; it has sprung free from the brains of happening.'
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 78 | Loc. 1194-1204  | Added on Tuesday, January 20, 2015, 11:56 PM

'The other shore' is enlightenment but enlightenment is also this shore, where we are right now. Does that irk ya? No? Read it again until it does. If Zen Buddhism were only the understanding that what we are right now is fine and dandy why do we bother practicing zazen and reading books and listening to teachers? It? s an important question. This was the burning question that our man Dogen,the founder of Japanese Soto Zen and one of the coolest Zen guys ever,took up when he began pursuing Buddhism in earnest: If we're already perfect as we are, why should we study Buddhism and practice Zen? No one could answer Dogen's question for him, and so Dogen had to find the truth for himself. In a sense, Dogen's entire multivolume Shobogenzo was his attempt to answer this one simple-sounding question. But that's his answer. What's yours? There are people who think of the spiritual life as a journey. Buddhism isn't like that. We may use the word path, but we're not trying to get anywhere. We're trying to fully experience the wonder and perfectness of being right here. Some of those other paths might claim to whisk you off to some magical place,and maybe they'll really do it. But when you get there you'll be just as baffled as you are right now.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 79 | Loc. 1204-8  | Added on Tuesday, January 20, 2015, 11:57 PM

BUDDHISM WON'T GIVE YOU THE ANSWER. Buddhism might help you find your own right question, but you've gotta supply your own answers. Sorry. No one else's answer will ever satisfy you,nor should it. But the real magic is that once you have your own true answer, you'll find you're not alone. As unique as your own true answer is,the one you find after questioning and questioning and questioning,it will be absolutely in tune with the answer Gautama Buddha found all those centuries ago, the answer Nagarjuna expounded upon, the answer Bodhidharma brought to China, and the one that Dogen wrote about in Japan.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 87 | Loc. 1320-24  | Added on Friday, January 23, 2015, 12:44 PM

For everyone,everyone,who first takes it up, zazen is tedious and awful. Your brain is in constant motion like there? s a hive of angry wasps in your head. There are moments when you're certain you're going to have to leap right off your cushion and run around the room singing the chorus of Hello, Dolly! just to keep from going utterly bananas. Anybody who doesn't feel that way about it, at least sometimes, is not doing the practice very sincerely. Zazen isn't about blissing out or going into an alpha brain-wave trance. It's about facing who and what you really are, in every single goddamn moment. And you aren't bliss, I'll tell you that right now. You're a mess. We all are.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 113 | Loc. 1723-27  | Added on Saturday, January 24, 2015, 12:57 PM

It? s like when The Who were on The Russell Harty Show in 1973. Pete Townshend pushed over one of his Marshall stack amps which fell with a thud and a crash of cymbals onto Keith Moon's drums, which in turn collapsed upon John Entwistle's Ampeg amp stacks, which also crashed to the studio floor. 'Now' is like Keith Moon's drums. 'The past' is Pete Townshend's amp, which created the motion by which Keith's drums now fall. 'The future' is John Entwistle's amplifiers. 'Self' only exists as a collective name for that series of smashes, crashes, and bangs. That's all.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 114 | Loc. 1741-44  | Added on Saturday, January 24, 2015, 01:00 PM

It takes far more energy to sustain anger than to let it go. It only seems difficult to drop your anger because you have built up a habit of responding in a certain way to certain situations. Reacting to anger is an addiction, pure and simple, just like smoking Marlboros.® Objectively it takes more resources to keep smoking than to stop. Yet giving it up seems much harder than continuing because you? re addicted.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 118 | Loc. 1807-9  | Added on Sunday, January 25, 2015, 12:45 AM

A guy walks up to a Zen master and asks, 'Is there life after death? The Zen Master says, 'How should I know' The guys replies indignantly, 'Because you? re a Zen master!' 'Yes,' says the Zen master, 'but not a dead one.'
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 143 | Loc. 2181-88  | Added on Monday, January 26, 2015, 12:25 AM

the institutional façade referred to as 'Buddhism.' And they know this precisely because of the social organization known as Buddhism. Neat, eh? Any good Zen Buddhist teacher will tell you right up front that the whole Zen Buddhist shebang, from robes to enlightenment to Dharma Transmission, is really a sham, ultimately not important in the least. And that? s what makes Zen Buddhism different from every other religion. As Johnny Rotten said in MOJO magazine, 'It isn't a rip-off if you tell everybody it's a rip-off.' Authority is easily abused. But authority can do good. It takes power to make the real changes needed in the world. A good person who is good at dealing with power can make the world a better place for everyone. Buddhism, though, should go beyond that. Buddhism is about letting people know they do not need to follow any authority. If you think you need an authority figure, go somewhere else.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 155 | Loc. 2364-66  | Added on Monday, January 26, 2015, 01:08 AM

Any kind of enlightenment that requires some mystical state is worse than useless. It just reinforces the belief that your 'self' has some kind of objective reality.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 167 | Loc. 2559-61  | Added on Monday, January 26, 2015, 01:39 AM

Sit zazen. And rest assured, by sitting staring at blank walls you can transform everything. Everything. This is not a metaphor. This is not exaggeration. This is the simple fact of the matter. ZEN REPLACES ALL OBJECTS OF BELIEF with one single thing: reality itself.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 172 | Loc. 2625-34  | Added on Monday, January 26, 2015, 06:31 PM

You can transform your life, and it is imperative that you do it. Because only you can do it. No guru can make your life right. No Zen master can show you the way. Only you have the power to make this place you? re living in right now a realm so beautiful even God himself couldn't dream of anything better. And doing this will transform the universe. It is up to you. It's not just your right; it's your duty. Only you can find the path and only you can walk it. To do this, you need to establish balance within yourself. You need a practice that will enable you to see yourself for what you truly are. Zazen is one way you can do that. And zazen can help you establish balance and keep it. People long for big thrills, peak experiences, deep insights. Some people take up zazen practice expecting that enlightenment will be the ultimate peak experience, the peak experience to beat all peak experiences. But real enlightenment is the most ordinary of the ordinary. And our ordinary, boring, pointless lives are incredibly, amazingly, astoundingly, relentlessly, mercilessly joyful.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 36 | Loc. 547-56  | Added on Thursday, January 29, 2015, 11:47 PM

Our way is not to sit to acquire something; it is to express our true nature. That is our practice.     If you want to express yourself, your true nature, there should be some natural and appropriate way of expression. Even swaying right and left as you sit down or get up from zazen is an expression of yourself. It is not preparation for practice, or relaxation after practice; it is part of the practice. So we should not do it as if it were preparing for something else. This should be true in your everyday life. To cook, or to fix some food, is not preparation, according to Dogen; it is practice. To cook is not just to prepare food for someone or for yourself; it is to express your sincerity. So when you cook you should express yourself in your activity in the kitchen. You should allow yourself plenty of time; you should work on it with nothing in your mind, and without expecting anything. You should just cook! That is also an expression of our sincerity, a part of our practice. It is necessary to sit in zazen, in this way, but sitting is not our only way. Whatever you do, it should be an expression of the same deep activity. We should appreciate what we are doing. There is no preparation for something else.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 40 | Loc. 606-12  | Added on Monday, February 09, 2015, 06:27 PM

    It is necessary for us to keep the constant way. Zen is not some kind of excitement, but concentration on our usual everyday routine. If you become too busy and too excited, your mind becomes rough and ragged. This is not good. If possible, try to be always calm and joyful and keep yourself from excitement. Usually we become busier and busier, day by day, year by year, especially in our modern world. If we revisit old, familiar places after a long time, we are astonished by the changes. It cannot be helped. But if we become interested in some excitement, or in our own change, we will become completely involved in our busy life, and we will be lost. But if your mind is calm and constant, you can keep yourself away from the noisy world even though you are in the midst of it. In the midst of noise and change, your mind will be quiet and stable.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 47 | Loc. 707-16  | Added on Tuesday, February 10, 2015, 12:49 AM

    So for us there is no other way to live in this world. I think this is quite true; and this is easy to accept, easy to understand, and easy to practice. If you compare the kind of life based on this practice with what is happening in this world, or in human society, you will find out just how valuable the truth Buddha left us is. It is quite simple, and practice is quite simple. But even so, we should not ignore it; its great value must be discovered. Usually when it is so simple we say, "Oh, I know that! It is quite simple. Everyone knows that." But if we do not find its value, it means nothing. It is the same as not knowing. The more you understand culture, the more you will understand how true and how necessary this teaching is. Instead of only criticizing your culture, you should devote your mind and body to practicing this simple way. Then society and culture will grow out of you. It may be all right for the people who are too attached to their culture to be critical. Their critical attitude means they are coming back to the simple truth left by Buddha. But our approach is just to be concentrated on a simple basic practice and a simple basic understanding of life. There should be no traces in our activity. We should not attach to some fancy ideas or to some beautiful things. We should not seek for something good. The truth is always near at hand, within your reach.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 48 | Loc. 734-37  | Added on Tuesday, February 24, 2015, 11:38 AM

    According to Christianity, every existence in nature is something which was created for or given to us by God. That is the perfect idea of giving. But if you think that God created man, and that you are somehow separate from God, you are liable to think you have the ability to create something separate, something not given by Him, For instance, we create airplanes and highways. And when we repeat, "I -create, I create, I create," soon we forget who is actually the "I" which creates the various things; we soon forget about God.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 50 | Loc. 759-64  | Added on Sunday, March 08, 2015, 11:25 PM

    And we should forget, day by day, what we have done; this is true non-attachment. And we should do something new. To do something new, of course we must know our past, and this is all right. But we should not keep holding onto anything we have done; we should only reflect on it. And we must have some idea of what we should do in the future. But the future is the future, the past is the past; now we should work on something new. This is our attitude, and how we should live in this world. This is " dana prajna paramita," to give something, or to create something for ourselves. So to do something through and through is to resume our true activity of creation. This is why we sit. If we do not forget this point, everything will be carried on beautifully. But once we forget this point, the world will be filled with confusion.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 74 | Loc. 1120-21  | Added on Monday, March 09, 2015, 09:24 AM

    "Our understanding of Buddhism is not just an intellectual understanding. True understanding is actual practice itself."
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 75 | Loc. 1137-42  | Added on Tuesday, March 10, 2015, 12:45 AM

    According to the traditional Buddhist understanding, our human nature is without ego. When we have no idea of ego, we have Buddha's view of life. Our egoistic ideas are delusion, covering our Buddha nature. We are always creating and following them, and in repeating this process over and over again, our life becomes completely occupied by ego-centered ideas. This is called karmic life, or karma. The Buddhist life should not be karmic life. The purpose of our practice is to cut off the karmic spinning mind. If you are trying to attain enlightenment, that is a part of karma, you are creating and being driven by karma, and you are wasting your time on your black cushion. According to Bodhi-dharma's understanding, practice based on any gaining idea is just a repetition of your karma.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 75 | Loc. 1149-57  | Added on Tuesday, March 10, 2015, 12:49 AM

But when you cannot believe in the meaning of the practice which you are doing in this moment, you cannot do anything. You are just wandering around the goal with your monkey mind. You are always looking for something without knowing what you are doing. If you want to see something, you should open your eyes. When you do not understand Bodhidharma's Zen, you are trying to look at something with your eyes closed. We do not slight the idea of attaining enlightenment, but the most important thing is this moment, not some day in the future. We have to make our effort in this moment. This is the most important thing for our practice.     Before Bodhidharma, the study of Buddha's teaching resulted in a deep and lofty philosophy of Buddhism, and people tried to attain its high ideals. This is a mistake. Bodhidharma discovered that it was a mistake to create some lofty or deep idea and then try to attain it by the practice of zazen. If that is our zazen, it is nothing different from our usual activity, or monkey mind. It looks like a very good, a very lofty and holy activity, but actually there is no difference between it and our monkey mind. That is the point that Bodhidharma emphasized.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 76 | Loc. 1166-71  | Added on Wednesday, March 11, 2015, 11:02 PM

     When we have the traditional spirit to follow the truth as it goes, and practice our way without any egoistic idea, then we will attain enlightenment in its true sense. And when we understand this point we will make our best effort in each moment. That is true understanding of Buddhism. So our understanding of Buddhism is not just an intellectual understanding. Our understanding at the same time is its own expression, is the practice itself. Not by reading or contemplation of philosophy, but only through practice, actual practice, can we understand what Buddhism is. Constantly, we should practice zen, with strong confidence in our true nature, breaking the chain of karmic activity and finding our place in the world of actual practice.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 77 | Loc. 1172-76  | Added on Wednesday, March 11, 2015, 11:03 PM

That everything changes is the basic truth for each existence. No one can deny this truth, and all the teaching of Buddhism is condensed within it. This is the teaching for all of us. Wherever we go this teaching is true. This teaching is also understood as the teaching of selflessness. Because each existence is in constant change, there is no abiding self. In fact, the self-nature of each existence is nothing but change itself, the self-nature of all existence. There is no special, separate self-nature for each existence. This is also called the teaching of Nirvana. When we realize the everlasting truth of "everything changes" and find our composure in it, we find ourselves in Nirvana.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 79 | Loc. 1202-4  | Added on Wednesday, March 11, 2015, 11:07 PM

We say, "In calmness there should be activity; in activity there should be calmness." Actually, they are the same thing; to say "calmness" or to say "activity" is just to express two different interpretations of one fact.
==========
Zen Mind, Beginner's Mind (Shunryu, Dixon Suzuki, Trudy Dixon and Richard Baker)
- Highlight on Page 88 | Loc. 1348-56  | Added on Friday, March 13, 2015, 05:19 PM

This kind of misunderstanding will vanish if you really understand emptiness means everything is always here. One whole being is not an accumulation of everything. It is impossible to divide one whole existence into parts. It is always here and always working. This is enlightenment. So there actually is no particular practice. In the sutra it says, "There are no eyes, no ears, no nose, no tongue, no body or mind?" This "no mind" is Zen mind, which includes everything.     The important thing in our understanding is to have a smooth, free-thinking way of observation. We have to think and to observe things without stagnation. We should accept things as they are without difficulty. Our mind should be soft and open enough to understand things as they are. When our thinking is soft, it is called imperturbable thinking. This kind of thinking is always stable. It is called mindfulness. Thinking which is divided in many ways is not true thinking. Concentration should be present in our thinking. This is mindfulness. Whether you have an object or not, your mind should be stable and your mind should not be divided. This is zazen.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 118 | Loc. 1807-13  | Added on Sunday, March 15, 2015, 10:35 AM

A guy walks up to a Zen master and asks, 'Is there life after death? The Zen Master says, 'How should I know' The guys replies indignantly, 'Because you? re a Zen master!' 'Yes,' says the Zen master, 'but not a dead one.' When people ask about life after death they're assuming they accurately understand life during life. But do they? Do you? This the one of the most important questions any of us can ask ourselves. When Gautama Buddha was asked about life after death, eternal existence, the origin of the universe, whether space is finite or infinite, and other such imponderables, he said, 'The question does not fit the case.' Being less formal, I might phrase the same thing this way: 'That's the wrong question, doofus!'
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 119 | Loc. 1820-25  | Added on Sunday, March 15, 2015, 10:37 AM

Our brain likes to label things. That? s its job. In our minds,and for the moment I'm using the words 'mind' and 'brain' to refer to the same thing,there is something we call 'me.' Our 'me' consists of all of our memories, dreams for the future, likes and dislikes, ideas and opinions, thoughts and perceptions, and so on. We have a whole catalogue of 'me' stuff like this. But 'me' is also our label for something ineffable, something we cannot put into words. It's a name we have for something we really don't understand but assume is there. Fundamentally we don't understand any of the things we give names to. I might call you 'Buttnugget' but Buttnugget is just a name I have for an image in my brain that I associate with you. It doesn't mean I have any idea what the world looks like through your eyes.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 120 | Loc. 1839-51  | Added on Sunday, March 15, 2015, 10:40 AM

Still, to say that when we die we return to the Great River of Being continues to miss the point. The notion of returning implies that right now we? re separate from the Great River of Being or from God or from anything else. We aren't. That bubble was always part of the river even when it appeared as a bubble. We don't return to God, because we never left God in the first place. Don't get too hooked on explanations, though. Explanations are never complete. When we die, we die. We never appear again. Dead, dead, dead. Gone, gone, gone. But in truth, we die all the time. Every moment of every day we die. Where is the person who slid out of your mother's womb greasy and purply-red and screaming like a banshee all those years ago? Are you that person? You have no memory of that day. It's a day that was over and done with a long, long time ago. Where is the person who lost5 your virginity? Where is the person who woke up bleary-eyed and crabby yesterday morning? Where is the person who will fill your casket? Our understanding of time is just plain wrong,and that misunderstanding leads us to believe that we could reincarnate, that we could live again after we die, that we could go to heaven, hell, or purgatory. That misunderstanding leads us to believe that it is even possible we might have a soul. But every one of these ideas is, ultimately, stupid. They really make no sense at all once we understand what time really is.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 153 | Loc. 2337-41  | Added on Sunday, March 15, 2015, 10:48 AM

The very idea of higher states of consciousness is absurd. Comparing one state of consciousness to another and saying one is 'higher' and the other is 'mundane' is like eating a banana and complaining it? s not a very good apple. The state of consciousness you have right now is 100 percent purely what it is. It is neither higher nor lower, better or worse, more or less significant, than the state of consciousness once achieved by some spaced-out swami who came back down and then wrote a book about his memories of it.
==========
Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality (Brad Warner)
- Highlight on Page 172 | Loc. 2631-49  | Added on Sunday, March 15, 2015, 11:10 AM

People long for big thrills, peak experiences, deep insights. Some people take up zazen practice expecting that enlightenment will be the ultimate peak experience, the peak experience to beat all peak experiences. But real enlightenment is the most ordinary of the ordinary. And our ordinary, boring, pointless lives are incredibly, amazingly, astoundingly, relentlessly, mercilessly joyful. You don? t need to do a damned thing to experience such joy either. You don't need to snort an ounce of coke, get a turkey-baster full of hot grease shoved up your ass, blow up the Washington Monument, win the Indy 500, or walk on the moon. You don't need to go hang-gliding over the Himalayas, or kayaking down the Amazon. You don't need to screw that oh-so-willing babe with the dark hair and the pouty lips or the smokin' seventeen-year-old on your brother's baseball team, and you don't need to party all night with the beautiful people. You don't need to do any of that stuff to know what it means to be alive. You're alive when you're sitting in your bedroom cleaning wax out of your ears. You're alive when you're looking at your turds floating in the toilet and noticing bits of last night's dinner in there. You're alive when you're at the supermarket wondering whether to go for the Hostess® Ho-Hos or the Little Debbies®. You're alive right now. Just be what you are, where you are. That's the most magical thing there is. The life you're living right now has joys even God could never know. No one else has ever lived this moment and no one else will ever live it. No one in the whole universe. Oh, there may have been people who stood on subway platforms looking at a book before. But they weren't you. It wasn't this book. They weren't as hungry for a nice slice of pizza as you are right now. They hadn't schtupped the people you have. They hadn't made the same stupid mistakes with their lives as you have. Nor have they felt the same joys. They haven't made happy the people you've made happy. The snot in their noses hasn't hardened into the same shapes that the snot in your nose has. Your life is yours alone, and to miss your life is the most tragic thing that could happen. So sit down, shut up, and take a look at it.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 211 | Loc. 3227-34  | Added on Sunday, September 07, 2014, 05:28 PM

Mu-ch? i and Liang-k'ai did many paintings of the Zen Patriarchs and masters, whom they represented for the most part as abandoned lunatics, scowling, shouting, loafing around, or roaring with laughter at drifting leaves. As favorite themes they adopted, as Zen figures, the two crazy hermits Han-shan and Shih-te, and the enormously rotund folk-god Pu-tai, to complete a marvelous assortment of happy tramps and rogues to exemplify the splendid nonsense and emptiness of the Zen life. Zen and"to some extent"Taoism seem to be the only spiritual traditions which feel secure enough to lampoon themselves, or to feel sufficiently un-self-conscious to laugh not only about their religion but in the midst of it. In these lunatic figures the Zen artists portray something slightly more than a parody of their own wu-shin or 'mindless' way of life, for as 'genius is to madness close allied' there is a suggestive parallel between the meaningless babble of the happy lunatic and the purposeless life of the Zen sage.
==========
The Way of Zen (Alan W. Watts)
- Highlight on Page 212 | Loc. 3236-48  | Added on Sunday, September 07, 2014, 05:30 PM

Thus the aimless life is the constant theme of Zen art of every kind, expressing the artist? s own inner state of going nowhere in a timeless moment. All men have these moments occasionally, and it is just then that they catch those vivid glimpses of the world which cast such a glow over the intervening wastes of memory"the smell of burning leaves on a morning of autumn haze, a flight of sunlit pigeons against a thundercloud, the sound of an unseen waterfall at dusk, or the single cry of some unidentified bird in the depths of a forest. In the art of Zen every landscape, every sketch of bamboo in the wind or of lonely rocks, is an echo of such moments. Where the mood of the moment is solitary and quiet it is called sabi.c When the artist is feeling depressed or sad, and in this peculiar emptiness of feeling catches a glimpse of something rather ordinary and unpretentious in its incredible 'suchness,' the mood is called wabi.d When the moment evokes a more intense, nostalgic sadness, connected with autumn and the vanishing away of the world, it is called aware.e And when the vision is the sudden perception of something mysterious and strange, hinting at an unknown never to be discovered, the mood is called yugen.f These extremely untranslatable Japanese words denote the four basic moods of furyu,g that is, of the general atmosphere of Zen 'taste' in its perception of the aimless moments of life.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 65 | Loc. 997-1000  | Added on Sunday, May 08, 2016, 12:15 PM

Rather than meditation being an activity that would take up an hour or so of my day, my daily life now became subsumed within the meditation. The practice of meditation was no longer a matter of becoming proficient in a technique. It was about sustaining a sensibility that encompassed everything I did. After a month or so, I reached a point where the meditation became completely unremarkable, nothing special at all.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 66 | Loc. 1000-1007  | Added on Sunday, May 08, 2016, 12:15 PM

By the time I left Switzerland, questions had become far more interesting to me than answers. For eight years, my Tibetan teachers had sought to convince me that the answers to the great questions of life were enshrined in their hermetic system of beliefs. The aim of their training had been to arrive at certainty: to reach a place where all questions had finally been resolved and all doubt vanquished. From their point of view, I had failed. While I valued the rich framework of Buddhist ideas they had given me, I could neither submit myself unquestioningly to the authority of the lamas nor uncritically accept their view of the world and the place of humans within it. The problem with certainty is that it is static; it can do little but endlessly reassert itself. Uncertainty, by contrast, is full of unknowns, possibilities, and risks. The certainties of Tibetan Buddhism had had a suffocating effect upon me, while the uncertainty celebrated in Korean Zen brought me vividly, if anxiously, to life.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 97 | Loc. 1480-85  | Added on Sunday, May 08, 2016, 04:31 PM

Kalamas, when you know for yourselves: these things are bad, these things are blamable; these things are censured by the wise; undertaken and observed, these things lead to harm and ill: then abandon them.” This unambiguous call for the valuing of uncertainty and the need to establish the truth of things for oneself rather than rely on the authority of others struck a deep chord within me. The Buddha encourages the Kalamas to observe for themselves the consequences of greed, hatred, and stupidity on human beings, so they can judge for themselves what thoughts and acts lead to harm and suffering and which do not. His sole criterion for evaluating a doctrine is whether it causes or mitigates suffering.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 97 | Loc. 1488-91  | Added on Sunday, May 08, 2016, 04:33 PM

The Kalama Sutta presents a vision of the Buddha’s teaching that goes against the grain of much Buddhist orthodoxy. Rather than deference to tradition and lineage, it celebrates self-reliance; rather than belief in doctrine, it stresses the importance of testing ideas to see if they work; and rather than insisting on a metaphysics of rebirth and karma, it suggests that this world might indeed be the only one there is.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 98 | Loc. 1491-1502  | Added on Sunday, May 08, 2016, 04:34 PM

the metaphysical questions the Buddha refuses to comment upon. These are some of the “big” questions to which religions claim to provide the answers: Is the universe eternal or not eternal? Is it finite or infinite? Is the mind the same as or different from the body? Does one continue to exist after death or not? The Buddha dismisses such questions, because to pursue them would not contribute to cultivating the kind of path he teaches. He compares a person who is preoccupied with such speculations to a man who has been wounded by a poisoned arrow but refuses to have it removed until he knows “the name and clan of the person who fired it; whether the bow was a longbow or a crossbow; whether the arrow was hoof-tipped, curved or barbed.” The only legitimate concern for such a person would be the removal of the arrow. The rest is irrelevant. In another Pali discourse the Buddha compares people who are obsessed with answering such questions to a group of blind men who are summoned by a king to describe an elephant. Each blind person is invited to touch a different part of the animal. The one holding the trunk declares that the elephant is a tube; the one feeling the side says that the elephant is a wall; while the one holding the tail is convinced that the elephant is a rope. Thus preoccupation with metaphysics not only fails to address the primary issue of suffering, but also leads to a partial and distorted picture of the complex totality of the human situation.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 127 | Loc. 1934-44  | Added on Tuesday, May 10, 2016, 08:32 AM

Gotama’s quest led him to abandon everything to do with his place—his king, his homeland, his social standing, his position in the family, his beliefs, his conviction of being a self in charge of a body and mind—but it did not result in psychotic collapse. For in relinquishing his place (ālaya), he arrived at a ground (hāna). But this ground is quite unlike the seemingly solid ground of a place. It is the contingent, transient, ambiguous, unpredictable, fascinating, and terrifying ground called “life.” Life is a groundless ground: no sooner does it appear, than it disappears, only to renew itself, then immediately break up and vanish again. It pours forth endlessly, like the river of Heraclitus into which one cannot step twice. If you try to grasp it, it slips away between your fingers. This groundless ground is not the absence of support. It supports you in a different way. Whereas a place can tie you down and close you off, this ground lets you go and opens you up. It does not stand still for a moment. To be supported by it, you have to be with it in a different way. Instead of standing firmly on your feet and holding on tight with both hands in order to feel secure in your place, here you have to dart across its liquid, shimmering surface like a long-legged fly, swim with its current like a fast-moving fish. Gotama compared the experience to “entering a stream.”
==========

Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 128 | Loc. 1960-62  | Added on Tuesday, May 10, 2016, 05:37 PM

Mindfulness focuses entirely on the specific conditions of one’s day-to-day experience. It is not concerned with anything transcendent or divine. It serves as an antidote to theism, a cure for sentimental piety, a scalpel for excising the tumor of metaphysical belief.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 129 | Loc. 1970-71  | Added on Tuesday, May 10, 2016, 05:38 PM

His awakening was not the result of intellectual theorizing alone but of sustained, focused attention to the texture and fabric of experience.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 129 | Loc. 1976-78  | Added on Tuesday, May 10, 2016, 05:39 PM

He had found a way of being in this world that was not conditioned by greed, hatred, or confusion. This was nirvana. The way was now open for him to engage with the world from the perspective of detachment, love, and lucidity.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 131 | Loc. 2005-9  | Added on Tuesday, May 10, 2016, 05:45 PM

I seem to be hardwired to experience my self and the world in this way. Yet despite the undeniable evidence of my own eyes, I know that the earth sets and rises, not the sun. Gotama did for the self what Copernicus did for the earth: he put it in its rightful place, despite its continuing to appear just as it did before. Gotama no more rejected the existence of the self than Copernicus rejected the existence of the earth. Instead, rather than regarding it as a fixed, non-contingent point around which everything else turned, he recognized that each self was a fluid, contingent process just like everything else.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 131 | Loc. 1996-2009  | Added on Tuesday, May 10, 2016, 05:46 PM

At the same time, one of the most unsettling memories of my youth is of an occasion when my mother inadvertently challenged my instinctive certainty of being “me.” It was Christmas, and I must have been about sixteen. My mother and her sister, my aunt Betty, were leafing through a volume of photographs on the kitchen table. They came to a snapshot of a man in military fatigues—eyes squinting against the desert sun, pipe clenched between teeth. My mother said to me: “If things had worked out differently, he would have been your father.” I thought: But if that man had been my father, would I have been me? This led me to wonder: If another of my actual father’s myriad spermatozoa impregnated my mother’s ovum, would the child born from such a mingling of chromosomes have been me? Or had the same spermatozoon burrowed home in her next ovarian cycle, would that baby have been me? Despite such unnerving glimpses of my own contingency, the conviction of my being a permanent, timeless witness has remained as steady and self-evident to me as the view I have of the sun rising every morning in the east, crossing the sky, then setting in the west. I seem to be hardwired to experience my self and the world in this way. Yet despite the undeniable evidence of my own eyes, I know that the earth sets and rises, not the sun. Gotama did for the self what Copernicus did for the earth: he put it in its rightful place, despite its continuing to appear just as it did before. Gotama no more rejected the existence of the self than Copernicus rejected the existence of the earth. Instead, rather than regarding it as a fixed, non-contingent point around which everything else turned, he recognized that each self was a fluid, contingent process just like everything else.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 132 | Loc. 2021-24  | Added on Tuesday, May 10, 2016, 05:48 PM

Gotama declared that his awakening to the contingent ground of life went “against the stream.” It was counterintuitive. It went against the instinctive sense of being a timeless witness of one’s experience. It contradicted the belief in an eternal soul and, by implication, in the transcendent reality of God. Rather than disassociating oneself from the world in order to achieve union with God, Gotama encouraged his followers to pay close, penetrating attention to the rise and fall of the phenomenal world itself.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 133 | Loc. 2028-33  | Added on Tuesday, May 10, 2016, 05:49 PM

The metaphors he used to describe the practice of mindfulness are earthy and practical. He compared the meditator to a skilled woodturner and butcher, men who have learned to use their tools with extraordinary precision, who can shape a piece of wood or dissect a carcass with minimal effort and maximum efficiency. Mindful awareness is not presented as a passive concentration on a single, steady object, but as a refined engagement with a shifting, complex world. Mindfulness is a skill that can be developed. It is a choice, an act, a response that springs from a quiet but curious intelligence. And it is empathetic, keenly sensitized to the peculiar texture of one’s own and others’ suffering.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 150 | Loc. 2289-91  | Added on Tuesday, May 10, 2016, 06:20 PM

Rather than dismiss the self as a fiction, Gotama presented it as a project to be realized. By “self” he referred not to the transcendent Self of the brahmins, which, by definition, cannot be anything other than what it eternally Is, but the functional, moral self that breathes and acts in this world.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 155 | Loc. 2368-76  | Added on Tuesday, May 10, 2016, 10:45 PM

The aim of mindfulness is to know suffering fully. It entails paying calm, unflinching attention to whatever impacts the organism, be it the song of a lark or the scream of a child, the bubbling of a playful idea or a twinge in the lower back. You attend not just to the outward stimuli themselves, but equally to your inward reactions to them. You do not condemn what you see as your failings or applaud what you regard as success. You notice things come, you notice them go. Over time, the practice becomes less a self-conscious exercise in meditation done at fixed periods each day and more a sensibility that infuses one’s awareness at all times. Mindfulness can have a sobering effect on the restless, jittery psyche. The stiller and more focused it becomes, the more I am able to peer into the sources of my febrile reactivity, to catch the first stirring of hatred before it overwhelms me with loathing and spite, to observe with ironic detachment the conceited babbling of the ego, to notice at its inception the self-demeaning story that could tip me into depression.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 156 | Loc. 2386-90  | Added on Wednesday, May 11, 2016, 07:09 AM

Mindfulness of suffering does not, however, lead to morbidity and despair. The more one internalizes a sense of the contingency of things, the less one is depressed and irked by pain (for it will pass) and the more one is awestruck by the presence of the simplest joys: to see a bud unfold, hear a wave rush over a beach, touch another person’s hand (these too will pass). As in great music, theater, and literature, the tragic sense of life evokes a strange, disquieting beauty. A self-portrait of Rembrandt, an adagio from a late Beethoven quartet, the agonies of King Lear do not depress but elevate me. They move me in my depths, arouse a keen perception of what it means to be alive rather than dead.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 159 | Loc. 2433-35  | Added on Wednesday, May 11, 2016, 07:20 AM

Turning the Wheel of Dhamma, the discourse Gotama delivered in the Deer Park in which he outlined his understanding of the Four Noble Truths, boils down to this: Embrace, Let go, Stop: Act!
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 173 | Loc. 2651-63  | Added on Friday, May 13, 2016, 07:32 AM

Whenever someone asks me whether I believe in God, I simply have no idea what the question means. Since those who ask tend to be educated and intelligent, I know they are not referring to a bearded old man sitting on a throne in the sky. But what are they referring to? I am just as puzzled by someone who says with equivalent conviction: “No, I do not believe in God.” What is it that they so emphatically do not believe in? The word God is such an ingrained cultural habit of speech that, as a native English speaker, it is assumed automatically that I know how to use it. “I rather find myself at a loss when a question of God is raised,” wrote Nanavira in a letter to Robert Brady. “I feel that I am expected to say something (even if it is only goodbye), and I don’t find anything to say.” I have read many theological tomes, which do their best to explain the meaning of God, but I am still not much the wiser. God is presented as the source and ground of everything. For Thomas Aquinas, God is esse ipsum: Being itself. But how do you believe in “the source and ground of everything” let alone in “Being itself”? The New Testament tells us that God is Love and that He sent his only begotten Son into the world. But how can the ultimate source and ground of everything have an emotion like “love” or an intention to “incarnate”? In what possible sense can Being itself be thought of as a Person? At this point, you learn that God is unknowable and utterly beyond any concept you can have of Him, that all descriptions of God are mere figures of speech, imperfect metaphors required to render intelligible something so mysterious and sublime that the human mind is incapable of ever grasping it. I had the funny feeling that I was being led around in circles.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 177 | Loc. 2710-19  | Added on Friday, May 13, 2016, 01:42 PM

But as soon as the object passes out of the field of vision or one shuts one’s eyes, that consciousness ceases. This is true of every kind of consciousness. “Just as a fire,” Gotama explained to Sati, “is reckoned by the particular condition dependent on which it burns—a log fire, a grass fire, a dung fire and so on—so too, consciousness is reckoned by the particular condition on which it arises.” Consciousness is an emergent, contingent, and impermanent phenomenon. It has no magical capacity to break free from the field of events out of which it springs. There are no wormholes in this intricate and fluid field through which one can wriggle out, either to reach union with God or move on to another existence after death. This is a field in which one is challenged to act; it is your actions alone that define you. There is no point in praying for divine guidance or assistance. That, as Gotama told Vasettha, would be like someone who wishes to cross the Aciravati River by calling out to the far bank: “Come here, other bank, come here!” No amount of “calling, begging, requesting or wheedling” will have any effect at all.
==========
Confession of a Buddhist Atheist (Stephen Batchelor)
- Highlight on Page 233 | Loc. 3573-79  | Added on Monday, May 16, 2016, 07:37 AM

What is it in Gotama’s teaching that was distinctively his own? There are four core elements of the Dhamma that cannot be derived from the Indian culture of his time. These are The principle of “this-conditionality, conditioned arising.” The process of the Four Noble Truths. The practice of mindful awareness. The power of self-reliance. These four axioms provide a sufficient ground for the kind of ethically committed, practically realized, and intellectually coherent way of life Gotama anticipated. They are the matrix that frames his vision of a new kind of culture, society, and civitas.
==========
Mindfulness in Plain English: 20th Anniversary Edition (Bhante Gunaratana)
- Highlight on Page 7 | Loc. 95-99  | Added on Thursday, May 19, 2016, 05:36 PM

Buddhism as a whole is quite different from the theological religions with which Westerners are most familiar. It is a direct entrance to a spiritual or divine realm, without assistance from deities or other “agents.” Its flavor is intensely clinical, much more akin to what we might call psychology than to what we would usually call religion. Buddhist practice is an ongoing investigation of reality, a microscopic examination of the very process of perception. Its intention is to pick apart the screen of lies and delusions through which we normally view the world, and thus to reveal the face of ultimate reality.
==========
Mindfulness in Plain English: 20th Anniversary Edition (Bhante Gunaratana)
- Highlight on Page 35 | Loc. 523-34  | Added on Friday, May 20, 2016, 07:21 PM

Even as you read these words, your body is aging. But you pay no attention to that. The book in your hand is decaying. The print is fading, and the pages are becoming brittle. The walls around you are aging. The molecules within those walls are vibrating at an enormous rate, and everything is shifting, going to pieces, and slowly dissolving. You pay no attention to that either. Then one day you look around you. Your skin is wrinkled and your joints ache. The book is a yellowed, faded thing; and the building is falling apart. So you pine for lost youth, cry when your possessions are gone. Where does this pain come from? It comes from your own inattention. You failed to look closely at life. You failed to observe the constantly shifting flow of the world as it passed by. You set up a collection of mental constructions—“me,” “the book,” “the building”—and you assumed that those were solid, real entities. You assumed that they would endure forever. They never do. But now you can tune into the constant change. You can learn to perceive your life as an ever-flowing movement. You can learn to see the continuous flow of all conditioned things. You can. It is just a matter of time and training. Our human perceptual habits are remarkably stupid in some ways. We tune out 99 percent of all the sensory stimuli we actually receive, and we solidify the remainder into discrete mental objects. Then we react to those mental objects in programmed, habitual ways.
==========
Mindfulness in Plain English: 20th Anniversary Edition (Bhante Gunaratana)
- Highlight on Page 41 | Loc. 623-27  | Added on Friday, May 20, 2016, 07:36 PM

You don’t need to figure everything out. Discursive thinking won’t free you from the trap. In meditation, the mind is purified naturally by mindfulness, by wordless bare attention. Habitual deliberation is not necessary to eliminate those things that are keeping you in bondage. All that is necessary is a clear, nonconceptual perception of what they are and how they work. That alone is sufficient to dissolve them. Concepts and reasoning just get in the way. Don’t think. See.
==========
The Coming of Conan the Cimmerian (Robert E. Howard)
- Highlight on Page 15 | Loc. 220-25  | Added on Wednesday, April 06, 2016, 09:21 PM

Conan’s philosophy is best expressed in one passage from Queen of the Black Coast: “In this world men struggle and suffer vainly, finding pleasure only in the bright madness of battle … Let me live deep while I live; let me know the rich juices of red meat and stinging wine on my palate, the hot embrace of white arms, the mad exultation of battle when the blue blades flame and crimson, and I am content. Let teachers and priests and philosophers brood over questions of reality and illusion. I know this: if life is illusion, then I am no less an illusion, and being thus, the illusion is real to me. I live, I burn with life, I love, I slay, and am content.”
==========
